### ISSUE TITLE
Consider publishing an automated build

### ISSUE THREAD

**Issue by tilgovi** [lyft/metadataproxy#10]
It would be great to have this as an automated build on the Docker Hub.

**Comment by ryan-lane** [comment]
Agreed. I'll take a look into how we can do that.

**Comment by ryan-lane** [comment]
Done. Travis will do docker pushes for master and approved branches. latest tag is based on master, otherwise tags are based on either tags or branches. So tag 1.1 will be 1.1 branch, whereas 1.1.1 would be from the 1.1.1 tag.
