### ISSUE TITLE
Fix docker push

### ISSUE THREAD

**Issue by ryan-lane** [lyft/metadataproxy#39]
Our docker push script isn't working right now, probably because the docker build isn't occuring. We need to add build in and try to bump the tag again.

**Comment by slikk66** [comment]
related to the PR? or is this something in the CI process

**Comment by ryan-lane** [comment]
Something in our CI process that we need to fix to get the docker image updated in docker hub. Just looping in your change because it won't show up in dockerhub till I fix this.

**Comment by slikk66** [comment]
👍 ok thanks!

**Comment by rvandegrift** [comment]
Any news here?  Would love to switch to the public registry.

**Comment by ryan-lane** [comment]
Fixed by https://github.com/lyft/metadataproxy/pull/54

**Comment by ryan-lane** [comment]
Newest tagged release (1.3.2) is in docker hub, and the latest tag points at master.
