### ISSUE TITLE
Config file not being used?

### ISSUE THREAD

**Issue by concat** [lyft/metadataproxy#58]
I have placed environment variables into my config file and sourced before running gunicorn.

For some reason, other than MOCK_API, the additional ones are not taking effect. As a result, I need to run "gunicorn metadataproxy:app --bind LOCAL_IP:PORT --workers=2 -k gevent" to use the local IP address rather than the loopback 127.0.01.

Bug or just something I don't understand (improvement to doc??).

**Comment by ryan-lane** [comment]
In your config file, did you export the variables, or just set them? Can you show me an example of what you're setting and running?

**Comment by concat** [comment]
So after digging into things, it seems that the run_server.sh script is needed to pull in the environment variables, right? This is not documented in the example.

**Comment by ryan-lane** [comment]
No. You just need to have them exported before you run the command. Are you running this through docker, or without docker? It's way easier to run this via docker, if you're running into any issues.

**Comment by ryan-lane** [comment]
Closing as stale.
