### ISSUE TITLE
DEFAULT_ROLE cannot be an ARN

### ISSUE THREAD

**Issue by lowjoel** [lyft/metadataproxy#85]
Hello,

After the refactor of roles.py, it appears that the DEFAULT_ROLE cannot be an ARN; in https://github.com/lyft/metadataproxy/blob/84c430ccdfcc58b8de84e7b7768646bd1d065a50/metadataproxy/roles.py#L197 only the IAM_ROLE variable is checked if it is an ARN, but not the DEFAULT_ROLE (if none is set.)

This means that IAM_ROLE can be an ARN or a short form, but the DEFAULT_ROLE can only be a short form. Any requests to the proxy would return 404 if an ARN is specified for DEFAULT_ROLE.

**Comment by tedder** [comment]
@ryan-lane I think you misread my comment, #87 does **not** fix this.

**Comment by ryan-lane** [comment]
@tedder doh, this is an annoying github thing. Since the PR was linked, it auto-closed the issue. Let me re-open. I know it doesn't solve it.

**Comment by tedder** [comment]
Oh, I see why. It isn't because it was linked, it's because I used the word "fix" right before mentioning it. doh, my bad!

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
