### ISSUE TITLE
IMDSv2 : PUT method is not supporting for http://169.254.169.254/latest/api/token

### ISSUE THREAD

**Issue by ystarikovich** [lyft/metadataproxy#98]
After upgrading underlying applications to new version of AWS SDK, call to the http://169.254.169.254/latest/api/token with PUT method is not working.

Which was introduced https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by ryan-lane** [comment]
For this we'd need to implement the SSRF mechanism in metadataproxy. It's a feature we want, but it's not on our roadmap right now.

If you're able to implement this, we'd definitely love to take a PR for it.

**Comment by ryan-lane** [comment]
Thanks for the report BTW! :)
